function out = func_ReadFiles(subj, ses, task_name, scanner)

ffiles = dir(fullfile(subj.dir, ses, 'func'));
ffiles = ffiles(3:end);
sfiles = dir(fullfile(subj.dir, ses, 'anat'));
sfiles = sfiles(3:end);

fdata = ffiles(contains({ffiles.name}, subj.name) & ...
    contains({ffiles.name}, ses) & ...
    contains({ffiles.name}, ['task-' task_name]) & ...
    contains({ffiles.name}, ['acq-' scanner]) & ...
    contains({ffiles.name}, 'bold.nii'));

sdata = sfiles(contains({sfiles.name}, subj.name) & ...
    contains({sfiles.name}, ses) & ...
    contains({sfiles.name}, ['acq-' scanner]) & ...
    contains({sfiles.name}, 'T1w.nii'));

fmap_files = dir(fullfile(subj.dir, ses, 'fmap'));
for i = 1:numel(fmap_files)
    if contains(fmap_files(i).name, 'magnitude1.nii')
        fmap_amp_file = fullfile(fmap_files(i).folder, fmap_files(i).name);
    elseif contains(fmap_files(i).name, 'phasediff.nii')
        fmap_pha_file = fullfile(fmap_files(i).folder, fmap_files(i).name);
    end
end

out = {fullfile(fdata.folder, fdata.name), ...
       fmap_amp_file, ...
       fmap_pha_file, ...
       fullfile(sdata.folder, sdata.name)};